sonar.projectKey=mustapha-smail-org_data-ingestion
sonar.projectName=CityPulse Data Ingestion

sonar.sources=src/main
sonar.tests=src/test
sonar.java.source=21
sonar.java.target=21

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/generated-sources/**
