server:
  port: 8082
spring:
  env:
    active: dev
  application:
    name: data-ingestion
log:
    level:
      root: INFO
      app: INFO
app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    username: ${KAFKA_USERNAME}
    password: ${KAFKA_PASSWORD}
    sasl-mechanism: ${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}

    topic:
      events: ${KAFKA_EVENTS_TOPIC}

    schema-registry:
      url: ${SCHEMA_REGISTRY_URL}
      username: ${SCHEMA_REGISTRY_USERNAME}
      password: ${SCHEMA_REGISTRY_PASSWORD}
      auto-register-schemas: true
api:
  opendata:
    paris:
      base-url: https://opendata.paris.fr
      dataset-id: que-faire-a-paris-
      whereClause: ""
ingestion:
  schedule:
    cron: "0 * * * * *"
#    cron: "0 0 * * * *"
    zone: "Europe/Paris"
