name: Main

on:
  push:
    branches: [main]

jobs:
  ci:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: mustapha-smail-org/deployment-workflows/.github/workflows/ci-main-java.yml@main
    with:
      service-name: data-ingestion
      java-version: '21'
      sonar-project-key: mustapha-smail-org_data-ingestion
      sonar-project-name: 'CityPulse Data Ingestion'
      sonar-organization: mustapha-smail-org
      jacoco-threshold: '70'
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
